<?php
$tabs = [
    "network"=>[
        [
            "id"=>"guestnet_tab_intruduct",
            "name"=>"Introduction",
            "module"=>"ssid_intro/ssid_intro"
        ],
        [
            "id"=>"guestnet_tab_1",
            "name"=>"SSID",
            "module"=>"ssid/ssid"
        ],
        [
            "id"=>"guestnet_tab_2",
            "name"=>"Scheduled",
            "module"=>"schedule/schedule"
        ],
        [
            "id"=>"guestnet_tab_9",
            "name"=>"Passcode",
            "module"=>"guest_passcode/guest_passcode"
        ]
    ]
];
