<?php

define('AdditionalInfo',[
    'private_ssid' => 'Startup Private SSID',
    'guest_ssid' => 'Startup Guest SSID',
    'wifi_street ' => 'Street',
    'wifi_state' => 'State',
    'wifi_contact' => 'Access Contact',
    'wifi_email' => 'Contact Email',
    'wifi-ins-time' => 'Preferred Install Time Slot',
    'wifi_site-name' => 'Name',
    'wifi_city' => 'City',
    'wifi_zip' => 'Zip',
    'wifi_phone' => 'Contact Phone',
    'wifi_prop_type' => 'Property Type',
    'wifi_ins_date' => 'Requested Install Date',
    'wifi_ins_start' => 'After Hours Start Time',
    'prod_order_type' => 'Order Type',
    'prod_in_ap_quant' => 'Indoor AP Quantity',
    'prod_content_filter' => 'Is Content Filtering Required?',
    'prod_circuit_type' => 'Circuit Type',
    'prod_guest' => 'QoS For Guest Network',
    'prod_telco' => 'Does the site have a rack where the Telco equipment is installed?',
    'prod_cabling' => 'Are the cabling paths from the Telco room into the site where Access Points will be mounted open and accessible?',
    'prod_flow_plan' => 'Floor Plan of the property',
    'prod_cover_area' => 'Pictures of the areas to be covered with WiFi',
    'prod_square_footage' => 'Indoor Square Footage',
    'prod_outdoor' => 'Outdoor AP Required?',
    'prod_guest_capacity' => 'Maximum Guest Capacity',
    'prod_circuit_size' => 'Circuit Size',
    'prod_private' => 'QoS for Private Network',
    'prod_rack_space' => 'Does the rack have available space for the new equipment?',
    'prod_wiring_paths' => 'If wiring paths are not open, is surface mounted wire molding is acceptable?',
    'prod_telco_room' => 'If wiring paths are not open, is surface mounted wire molding is acceptable?',
    'qq_ceiling_hight' => 'Ceiling Heights',
    'qq_int_wall' => 'Interior Wall Type ',
    'qq_communicate_other' => 'Do you have other networks that need to communicate through this network?',
    'qq_residential' => 'Is this site a residential property?',
    'qq_atmospheric' => 'Does this site have atmospheric conditioning to control temperature and humidity?',
    'qq_ceiling_type' => 'Ceiling Type',
    'qq_ext_wall' => 'Exterior Wall Type ',
    'qq_customizable_ui' => 'Do you require a fully customizable UI?',
    'qq_warehouse' => 'Is this site a warehouse?',
    'qq_IoT_devices' => 'Are there IoT devices that need to be controlled or monitored by the system? '
]);