// Countries
var country_arr = new Array("United States of America", "Afghanistan", "Albania", "Algeria", "American Samoa", "Angola", "Anguilla", "Antartica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Ashmore and Cartier Island", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Clipperton Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czeck Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Europa Island", "Falkland Islands (Islas Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon", "Gambia, The", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Glorioso Islands", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City)", "Honduras", "Hong Kong", "Howland Island", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Ireland, Northern", "Israel", "Italy", "Jamaica", "Jan Mayen", "Japan", "Jarvis Island", "Jersey", "Johnston Atoll", "Jordan", "Juan de Nova Island", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Man, Isle of", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Midway Islands", "Moldova", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcaim Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romainia", "Russia", "Rwanda", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Scotland", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and South Sandwich Islands", "Spain", "Spratly Islands", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Tobago", "Toga", "Tokelau", "Tonga", "Trinidad", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands", "Wales", "Wallis and Futuna", "West Bank", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");

// States
var s_a = new Array();
s_a[0] = "";
s_a[1] = "Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|District of Columbia|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming";
s_a[2] = "No states available";
s_a[3] = "No states available";
s_a[4] = "No states available";
s_a[5] = "No states available";
s_a[6] = "No states available";
s_a[7] = "No states available";
s_a[8] = "No states available";
s_a[9] = "No states available";
s_a[10] = "No states available";
s_a[11] = "No states available";
s_a[12] = "No states available";
s_a[13] = "No states available";
s_a[14] = "No states available";
s_a[15] = "No states available";
s_a[16] = "No states available";
s_a[17] = "No states available";
s_a[18] = "No states available";
s_a[19] = "No states available";
s_a[20] = "No states available";
s_a[21] = "No states available";
s_a[22] = "No states available";
s_a[23] = "No states available";
s_a[24] = "No states available";
s_a[25] = "No states available";
s_a[26] = "No states available";
s_a[27] = "No states available";
s_a[28] = "No states available";
s_a[29] = "No states available";
s_a[30] = "No states available";
s_a[31] = "No states available";
s_a[32] = "No states available";
s_a[33] = "No states available";
s_a[34] = "No states available";
s_a[35] = "No states available";
s_a[36] = "No states available";
s_a[37] = "No states available";
s_a[38] = "No states available";
s_a[39] = "No states available";
s_a[40] = "No states available";
s_a[41] = "No states available";
s_a[42] = "No states available";
s_a[43] = "No states available";
s_a[44] = "No states available";
s_a[45] = "No states available";
s_a[46] = "No states available";
s_a[47] = "No states available";
s_a[48] = "No states available";
// <!-- -->
s_a[49] = "No states available";
s_a[50] = "No states available";
s_a[51] = "No states available";
s_a[52] = "No states available";
s_a[53] = "No states available";
s_a[54] = "No states available";
s_a[55] = "No states available";
s_a[56] = "No states available";
s_a[57] = "No states available";
s_a[58] = "No states available";
s_a[59] = "No states available";
s_a[60] = "No states available";
s_a[61] = "No states available";
s_a[62] = "No states available";
// <!-- -->
s_a[63] = "No states available";
s_a[64] = "No states available";
s_a[65] = "No states available";
s_a[66] = "No states available";
s_a[67] = "No states available";
s_a[68] = "No states available";
s_a[69] = "No states available";
s_a[70] = "No states available";
s_a[71] = "No states available";
s_a[72] = "No states available";
s_a[73] = "No states available";
s_a[74] = "No states available";
s_a[75] = "No states available";
s_a[76] = "No states available";
s_a[77] = "No states available";
s_a[78] = "No states available";
s_a[79] = "No states available";
s_a[80] = "No states available";
s_a[81] = "No states available";
s_a[82] = "No states available";
s_a[83] = "No states available";
s_a[84] = "No states available";
s_a[85] = "No states available";
s_a[86] = "No states available";
s_a[87] = "No states available";
s_a[88] = "No states available";
s_a[89] = "No states available";
s_a[90] = "No states available";
s_a[91] = "No states available";
s_a[92] = "No states available";
s_a[93] = "No states available";
s_a[94] = "No states available";
s_a[95] = "No states available";
s_a[96] = "No states available";
s_a[97] = "No states available";
s_a[98] = "No states available";
s_a[99] = "No states available";
s_a[100] = "No states available";
s_a[101] = "No states available";
s_a[102] = "No states available";
s_a[103] = "No states available";
s_a[104] = "No states available";
s_a[105] = "No states available";
s_a[106] = "No states available";
s_a[107] = "No states available";
s_a[108] = "No states available";
s_a[109] = "No states available";
s_a[110] = "No states available";
s_a[111] = "No states available";
s_a[112] = "No states available";
s_a[113] = "No states available";
s_a[114] = "No states available";
s_a[115] = "No states available";
s_a[116] = "No states available";
s_a[117] = "No states available";
s_a[118] = "No states available";
s_a[119] = "No states available";
s_a[120] = "No states available";
s_a[121] = "No states available";
s_a[122] = "No states available";
s_a[123] = "No states available";
s_a[124] = "No states available";
s_a[125] = "No states available";
s_a[126] = "No states available";
s_a[127] = "No states available";
s_a[128] = "No states available";
s_a[129] = "No states available";
s_a[130] = "No states available";
s_a[131] = "No states available";
s_a[132] = "No states available";
s_a[133] = "No states available";
s_a[134] = "No states available";
s_a[135] = "No states available";
s_a[136] = "No states available";
s_a[137] = "No states available";
s_a[138] = "No states available";
s_a[139] = "No states available";
s_a[140] = "No states available";
s_a[141] = "No states available";
s_a[142] = "No states available";
s_a[143] = "No states available";
s_a[144] = "No states available";
s_a[145] = "No states available";
s_a[146] = "No states available";
s_a[147] = "No states available";
s_a[148] = "No states available";
s_a[149] = "No states available";
s_a[150] = "No states available";
s_a[151] = "No states available";
s_a[152] = "No states available";
s_a[153] = "No states available";
s_a[154] = "No states available";
s_a[155] = "No states available";
s_a[156] = "No states available";
s_a[157] = "No states available";
s_a[158] = "No states available";
s_a[159] = "No states available";
s_a[160] = "No states available";
s_a[161] = "No states available";
s_a[162] = "No states available";
s_a[163] = "No states available";
s_a[164] = "No states available";
s_a[165] = "No states available";
s_a[166] = "No states available";
s_a[167] = "No states available";
s_a[168] = "No states available";
s_a[169] = "No states available";
s_a[170] = "No states available";
s_a[171] = "No states available";
s_a[172] = "No states available";
s_a[173] = "No states available";
s_a[174] = "No states available";
s_a[175] = "No states available";
s_a[176] = "No states available";
s_a[177] = "No states available";
s_a[178] = "No states available";
s_a[179] = "No states available";
s_a[180] = "No states available";
s_a[181] = "No states available";
s_a[182] = "No states available";
s_a[183] = "No states available";
s_a[184] = "No states available";
s_a[185] = "No states available";
s_a[186] = "No states available";
s_a[187] = "No states available";
s_a[188] = "No states available";
s_a[189] = "No states available";
s_a[190] = "No states available";
s_a[191] = "No states available";
s_a[192] = "No states available";
s_a[193] = "No states available";
s_a[194] = "No states available";
s_a[195] = "No states available";
s_a[196] = "No states available";
s_a[197] = "No states available";
s_a[198] = "No states available";
s_a[199] = "No states available";
s_a[200] = "No states available";
s_a[201] = "No states available";
s_a[202] = "No states available";
s_a[203] = "No states available";
s_a[204] = "No states available";
s_a[205] = "No states available";
s_a[206] = "No states available";
s_a[207] = "No states available";
s_a[208] = "No states available";
s_a[209] = "No states available";
s_a[210] = "No states available";
s_a[211] = "No states available";
s_a[212] = "No states available";
s_a[213] = "No states available";
s_a[214] = "No states available";
s_a[215] = "No states available";
s_a[216] = "No states available";
s_a[217] = "No states available";
s_a[218] = "No states available";
s_a[219] = "No states available";
s_a[220] = "No states available";
s_a[221] = "No states available";
s_a[222] = "No states available";
s_a[223] = "No states available";
s_a[224] = "No states available";
s_a[225] = "No states available";
s_a[226] = "No states available";
s_a[227] = "No states available";
s_a[228] = "No states available";
s_a[229] = "No states available";
s_a[230] = "No states available";
s_a[231] = "No states available";
s_a[232] = "No states available";
s_a[233] = "No states available";
s_a[234] = "No states available";
s_a[235] = "No states available";
s_a[236] = "No states available";
s_a[237] = "No states available";
s_a[238] = "No states available";
s_a[239] = "No states available";
s_a[240] = "No states available";
s_a[241] = "No states available";
s_a[242] = "No states available";
s_a[243] = "No states available";
s_a[244] = "No states available";
s_a[245] = "No states available";
s_a[246] = "No states available";
s_a[247] = "No states available";
s_a[248] = "No states available";
s_a[249] = "No states available";
s_a[250] = "No states available";
s_a[251] = "No states available";
s_a[252] = "No states available";
/* s_a[252] = "No states available"; */

function populateStates(countryElementId, stateElementId) {

    var selectedCountryIndex = document.getElementById(countryElementId).selectedIndex;

    var stateElement = document.getElementById(stateElementId);

    stateElement.length = 0; // Fixed by Julian Woods
    stateElement.options[0] = new Option('Select State', '');
    stateElement.selectedIndex = 0;

    var state_arr = s_a[selectedCountryIndex].split("|");

    for (var i = 0; i < state_arr.length; i++) {
        stateElement.options[stateElement.length] = new Option(state_arr[i], state_arr[i]);
    }
}

function populateCountries(countryElementId, stateElementId) {
    // given the id of the <select> tag as function argument, it inserts <option> tags
    var countryElement = document.getElementById(countryElementId);
    countryElement.length = 0;
    countryElement.options[0] = new Option('Select Country', '');
    countryElement.selectedIndex = 0;
    for (var i = 0; i < country_arr.length; i++) {
        countryElement.options[countryElement.length] = new Option(country_arr[i], country_arr[i]);
    }

    // Assigned all countries. Now assign event listener for the states.

    if (stateElementId) {
        countryElement.onchange = function() {
            populateStates(countryElementId, stateElementId);
        };
    }
}